

service: circleCiApp


provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: handler.hello

    events:
     - http:
          path: /hello
          method: get


